version: "3.8"

services:
  my-database:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: my-database-container
    volumes:
      # Mount the SQL file so it's available for initialization
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: mygas
      POSTGRES_PASSWORD: mygas
      POSTGRES_DB: mygas
    ports:
      - "5432:5432"