version: "3.8"

services:
  my-database:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: my-database-container
    volumes:
      # Mount the SQL file so it's available for initialization
      - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"